package models

// AITask represents a task generated by AI with metadata
type AITask struct {
	Text          string `json:"text"`           // Task description
	Priority      string `json:"priority"`       // "high", "medium", "low"
	EstimatedTime string `json:"estimated_time"` // e.g., "15 minutes", "1 hour"
	Category      string `json:"category"`       // Optional category/tag
}

// AITaskBreakdownRequest represents the request for AI task breakdown
type AITaskBreakdownRequest struct {
	Goal string `json:"goal" binding:"required"` // User's goal/task
}

// AITaskBreakdownResponse represents the response with generated tasks
type AITaskBreakdownResponse struct {
	Success        bool     `json:"success"`
	Goal           string   `json:"goal"`
	SuggestedTasks []AITask `json:"suggested_tasks"`
	Message        string   `json:"message,omitempty"`
}

// CreateAITasksRequest represents request to create multiple todos from AI tasks
type CreateAITasksRequest struct {
	Tasks  []AITask `json:"tasks" binding:"required"`
	ListId *string  `json:"list_id,omitempty"` // Optional: if provided, creates todos in specific list
}
